# Generated by Django 5.0.14 on 2025-09-02 16:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date', 'title'], 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekter'},
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Valgfrit - kunde navn (anonymt eller med tilladelse)', max_length=255, verbose_name='Kunde navn'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text="F.eks. 'København', 'Privat bolig', eller 'Erhverv'", max_length=255, verbose_name='Lokation'),
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.TextField(blank=True, help_text="F.eks. 'Jatoba træ', 'Lærk', 'Eg', osv.", verbose_name='Materialer brugt'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('renovation', 'Renovering'), ('nybyggeri', 'Nybyggeri'), ('tilbygning', 'Tilbygning'), ('reparation', 'Reparation'), ('haandvaerk', 'Håndværk'), ('andet', 'Andet')], default='haandvaerk', max_length=100, verbose_name='Projekt type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, help_text='Hvornår blev projektet færdiggjort?', null=True, verbose_name='Projekt dato'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Beskriv arbejdet, materialer og proces', verbose_name='Projekt beskrivelse'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Vis dette projekt fremhævet på forsiden', verbose_name='Featured projekt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.BooleanField(default=True, help_text='Skal projektet vises på hjemmesiden?', verbose_name='Synlig på hjemmeside'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(help_text='Automatisk genereret fra titlen', max_length=255, unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text="F.eks. 'Køkken renovering' eller 'Træ terrasse'", max_length=255, verbose_name='Projekt titel'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Valgfri beskrivelse af billedet', max_length=500, verbose_name='Billedtekst')),
                ('alt_text', models.CharField(blank=True, help_text='Beskrivelse for skærmlæsere', max_length=255, verbose_name='Alt tekst')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Billede')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projekt billede',
                'verbose_name_plural': 'Projekt billeder',
            },
        ),
    ]
