# Generated by Django 5.0.14 on 2025-09-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='site',
        ),
    ]
