# Generated by Django 5.0.14 on 2025-09-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectpage_options_projectpage_collection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='collection',
        ),
    ]
