# Generated by Django 5.0.14 on 2025-09-11 14:21

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_site_field'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Beskriv arbejdet, materialer og proces', verbose_name='Projekt beskrivelse')),
                ('materials', models.TextField(blank=True, help_text="F.eks. 'Jatoba træ', 'Lærk', 'Eg', osv.", verbose_name='Materialer brugt')),
                ('client_name', models.CharField(blank=True, help_text='Valgfrit - kunde navn (anonymt eller med tilladelse)', max_length=255, verbose_name='Kunde navn')),
                ('location', models.CharField(blank=True, help_text="F.eks. 'København', 'Privat bolig', eller 'Erhverv'", max_length=255, verbose_name='Lokation')),
                ('featured', models.BooleanField(default=False, help_text='Vis dette projekt fremhævet på forsiden', verbose_name='Featured projekt')),
                ('project_date', models.DateField(blank=True, help_text='Hvornår blev projektet færdiggjort?', null=True, verbose_name='Projekt dato')),
            ],
            options={
                'verbose_name': 'Projekt Side',
                'verbose_name_plural': 'Projekt Sider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Valgfri beskrivelse af billedet', max_length=500, verbose_name='Billedtekst')),
                ('alt_text', models.CharField(blank=True, help_text='Beskrivelse for skærmlæsere', max_length=255, verbose_name='Alt tekst')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Billede')),
                ('project_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='projects.projectpage', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projekt billede',
                'verbose_name_plural': 'Projekt billeder',
            },
        ),
        migrations.CreateModel(
            name='ProjectPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='projects.projectpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='projects.ProjectPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
