# Generated by Django 5.0.14 on 2025-09-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_convert_projects_to_pages_fixed'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'permissions': [('can_approve_projects', 'Can approve projects'), ('can_manage_project_budget', 'Can manage project budget'), ('can_set_project_priority', 'Can set project priority')], 'verbose_name': 'Projekt Side', 'verbose_name_plural': 'Projekt Sider'},
        ),
        migrations.AddField(
            model_name='projectpage',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Vælg projektets kategori (f.eks. Bolig, Erhverv, Renovering)', null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailcore.collection', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimeret budget for projektet (DKK)', max_digits=10, null=True, verbose_name='Estimeret budget'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='priority',
            field=models.CharField(choices=[('low', 'Lav'), ('medium', 'Medium'), ('high', 'Høj'), ('urgent', 'Akut')], default='medium', help_text='Projekt prioritet for planlægning', max_length=10, verbose_name='Prioritet'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_status',
            field=models.CharField(choices=[('planning', 'Planlægning'), ('in_progress', 'I gang'), ('completed', 'Færdig'), ('on_hold', 'På pause'), ('cancelled', 'Annulleret')], default='planning', help_text='Nuværende projekt status', max_length=20, verbose_name='Status'),
        ),
    ]
