# Production override file
# Use: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  web:
    environment:
      DEBUG: "False"
      SECURE_SSL_REDIRECT: "True"
      LOAD_BASELINE: "false"
      # Production superuser should be configured via environment
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL:-admin@jcleemannbyg.dk}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD:-admin123}