# Generated by Django 5.0.14 on 2025-09-08 08:07

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text="e.g. 'JCleemann Byg', 'Peters Construction'", max_length=255, verbose_name='Business Name')),
                ('description', models.TextField(blank=True, help_text='Brief description of the construction business', verbose_name='Business Description')),
                ('contact_email', models.EmailField(blank=True, help_text='Primary contact email for this business', max_length=254, verbose_name='Contact Email')),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact phone number', max_length=20, verbose_name='Phone Number')),
                ('theme', models.CharField(choices=[('forest', 'Forest Green'), ('wood', 'Wood Brown'), ('slate', 'Slate Gray')], default='forest', help_text="Visual theme for this tenant's website", max_length=20, verbose_name='Website Theme')),
                ('cvr_number', models.CharField(blank=True, help_text='Danish CVR business registration number', max_length=20, verbose_name='CVR Number')),
                ('address', models.TextField(blank=True, help_text='Physical business address', verbose_name='Business Address')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active and accessible', verbose_name='Active')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
