# Generated by Django 5.0.14 on 2025-09-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_finalize_theme_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='theme',
            field=models.ForeignKey(blank=True, help_text="Visual theme for this tenant's website", null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.theme', verbose_name='Website Theme'),
        ),
    ]
