# Generated by Django 5.0.14 on 2025-09-02 13:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('hero', 5), ('trust_badges', 9), ('featured_projects', 12), ('testimonials', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Anchor id to scroll to', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background_image', 2), ('cta_text', 3), ('cta_anchor', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug of a Project to feature'}), 11: ('wagtail.blocks.StructBlock', [[('project_slug', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.TextBlock', (), {}), 14: ('wagtail.blocks.ListBlock', (13,), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
