# Generated by Django 5.0.14 on 2025-09-02 15:41

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0099_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('hero', 4), ('trust_badges', 8), ('featured_projects', 11), ('testimonials', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Anchor id to scroll to', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('cta_text', 2), ('cta_anchor', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug of a Project to feature'}), 10: ('wagtail.blocks.StructBlock', [[('project_slug', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
