# Generated by Django 4.2.24 on 2025-09-08 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('wagtailcore', '0100_merge_20250908_1315'),
        ('pages', '0005_alter_homepage_body_alter_modularpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='JCleemann Byg', help_text='Navn der vises på websitet', max_length=255, verbose_name='Firmanavn')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email adresse')),
                ('cvr', models.CharField(blank=True, max_length=20, verbose_name='CVR nummer')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('default_theme', models.CharField(choices=[('forest', 'Forest'), ('wood', 'Wood'), ('slate', 'Slate')], default='forest', help_text='Standardtema for websitet (kan overstyres pr. side)', max_length=20, verbose_name='Standard tema')),
                ('logo', models.ForeignKey(blank=True, help_text='Firmalogo der vises i headeren', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Generelle indstillinger',
                'verbose_name_plural': 'Generelle indstillinger',
            },
        ),
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
    ]
