# Generated by Django 5.0.14 on 2025-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_contactpage_contact_form_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_services_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_button_text',
            field=models.CharField(default='Få et tilbud', max_length=50, verbose_name='Footer CTA knap tekst'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_text',
            field=models.CharField(default='Kontakt os i dag for et uforpligtende tilbud på dit projekt.', help_text='Call-to-action beskrivelse i footer', max_length=255, verbose_name='Footer CTA tekst'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_cta_title',
            field=models.CharField(default='Klar til at starte?', help_text='Call-to-action titel i footer', max_length=100, verbose_name='Footer CTA titel'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Åbningstider der vises i footer (en linje per dag)', verbose_name='Åbningstider'),
        ),
    ]
