# Generated by Django 5.0.14 on 2025-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_cta_button_text',
            field=models.CharField(blank=True, default='Få et tilbud', max_length=50, verbose_name='Footer CTA knap tekst'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_cta_text',
            field=models.CharField(blank=True, default='Kontakt os i dag for et uforpligtende tilbud på dit projekt.', help_text='Call-to-action beskrivelse i footer', max_length=255, verbose_name='Footer CTA tekst'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_cta_title',
            field=models.CharField(blank=True, default='Klar til at starte?', help_text='Call-to-action titel i footer', max_length=100, verbose_name='Footer CTA titel'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='opening_hours',
            field=models.TextField(blank=True, default='', help_text='Åbningstider der vises i footer (en linje per dag)', verbose_name='Åbningstider'),
        ),
    ]
