# Generated by Django 5.1.2 on 2025-01-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_sitesettings_footer_cta_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_choice',
            field=models.CharField(
                choices=[
                    ('inter-playfair', 'Inter + Playfair Display (Professionel)'),
                    ('inter-georgia', 'Inter + Georgia (Klassisk)'),
                    ('system-fonts', 'System skrifttyper (Hurtig)'),
                    ('roboto-lora', 'Roboto + Lora (Moderne)'),
                    ('open-sans-merriweather', 'Open Sans + Merriweather (Læsbar)'),
                ],
                default='inter-playfair',
                help_text='Skrifttype kombination for websitet',
                max_length=30,
                verbose_name='Skrifttype'
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_preview',
            field=models.BooleanField(
                default=True,
                help_text='Tillad forhåndsvisning af ændringer før de publiceres',
                verbose_name='Aktivér forhåndsvisning'
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='preview_url_override',
            field=models.CharField(
                blank=True,
                help_text='Valgfri specifik URL for forhåndsvisning (lad være tom for standard)',
                max_length=255,
                verbose_name='Forhåndsvisning URL'
            ),
        ),
    ]