# Generated by Django 5.0.14 on 2025-09-13 15:22

import django.db.models.deletion
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_homepage_body_alter_modularpage_body_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Kort introduktion til virksomheden', verbose_name='Intro tekst')),
                ('company_story', wagtail.fields.RichTextField(blank=True, help_text='Fortæl historien om hvordan virksomheden blev grundlagt og udviklet', verbose_name='Virksomhedens historie')),
                ('mission_statement', wagtail.fields.RichTextField(blank=True, help_text='Virksomhedens mission og formål', verbose_name='Mission')),
                ('vision_statement', wagtail.fields.RichTextField(blank=True, help_text='Virksomhedens vision for fremtiden', verbose_name='Vision')),
                ('core_values', wagtail.fields.RichTextField(blank=True, help_text='De grundlæggende værdier virksomheden bygger på', verbose_name='Kernev værdierne')),
                ('years_in_business', models.PositiveIntegerField(blank=True, help_text='Antal år virksomheden har været aktiv', null=True, verbose_name='År i branchen')),
                ('projects_completed', models.PositiveIntegerField(blank=True, help_text='Antal projekter der er gennemført', null=True, verbose_name='Gennemførte projekter')),
                ('team_size', models.PositiveIntegerField(blank=True, help_text='Antal medarbejdere', null=True, verbose_name='Teamstørrelse')),
                ('service_areas', wagtail.fields.RichTextField(blank=True, help_text='Geografiske områder hvor virksomheden opererer', verbose_name='Serviceområder')),
                ('specializations', wagtail.fields.RichTextField(blank=True, help_text='Områder hvor virksomheden har særlig ekspertise', verbose_name='Specialiseringer')),
                ('insurance_info', wagtail.fields.RichTextField(blank=True, help_text='Information om virksomhedens forsikringer', verbose_name='Forsikring')),
                ('licenses_info', wagtail.fields.RichTextField(blank=True, help_text='Relevante licenser og tilladelser', verbose_name='Licenser')),
                ('sustainability_commitment', wagtail.fields.RichTextField(blank=True, help_text='Virksomhedens tilgang til bæredygtig byggeri', verbose_name='Bæredygtighed')),
                ('body', wagtail.fields.StreamField([('hero_v2', 12), ('richtext_section', 15), ('team_section', 22), ('company_milestones', 29), ('certifications_section', 36), ('company_stats', 45), ('features', 52), ('testimonials_snippets', 55), ('cta', 60), ('image_gallery', 66), ('faq', 72)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hovedoverskrift for hero sektionen', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Undertitel eller beskrivende tekst', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Tekst for primær knap (fx 'Få et tilbud')", 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Side som primær knap linker til', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Tekst for sekundær knap (fx 'Se projekter')", 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Side som sekundær knap linker til', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Billede der vises under teksten', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('surface', 'Surface (Standard)'), ('surface-soft', 'Surface Soft'), ('hero', 'Hero Gradient'), ('base-200', 'Base 200'), ('base-300', 'Base 300')], 'help_text': 'Baggrundsfarve for sektionen', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small (py-10)'), ('md', 'Medium (py-16)'), ('lg', 'Large (py-24)')], 'help_text': 'Vertikal spacing for sektionen', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('narrow', 'Narrow (max-w-3xl)'), ('normal', 'Normal (max-w-5xl)'), ('wide', 'Wide (max-w-7xl)')], 'help_text': 'Bredde af indholdet', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Vis en subtil top divider', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('background', 7), ('spacing', 8), ('container', 9), ('divider', 10)]], {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('primary_text', 2), ('primary_page', 3), ('secondary_text', 4), ('secondary_page', 5), ('image', 6), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for tekstsektionen', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'help_text': 'Rich text indhold med formatering'}), 15: ('wagtail.blocks.StructBlock', [[('heading', 13), ('body', 14), ('style', 11)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Vores team', 'help_text': 'Overskrift for team sektionen', 'required': False}), 17: ('wagtail.blocks.TextBlock', (), {'help_text': 'Undertitel eller beskrivelse af teamet', 'required': False}), 18: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.TeamMember'}), 19: ('wagtail.blocks.ListBlock', (18,), {'help_text': 'Vælg teammedlemmer der skal vises'}), 20: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Vis alle teammedlemmer automatisk (ignorerer valgte medlemmer)', 'required': False}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 kolonner'), ('3', '3 kolonner'), ('4', '4 kolonner')], 'help_text': 'Antal kolonner for layout'}), 22: ('wagtail.blocks.StructBlock', [[('heading', 16), ('subheading', 17), ('team_members', 19), ('show_all_members', 20), ('columns', 21), ('style', 11)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'default': 'Vores rejse', 'help_text': 'Overskrift for milepæle sektionen', 'required': False}), 24: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse af virksomhedens udvikling', 'required': False}), 25: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.CompanyMilestone'}), 26: ('wagtail.blocks.ListBlock', (25,), {'help_text': 'Vælg milepæle der skal vises'}), 27: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Vis alle milepæle automatisk (ignorerer valgte milepæle)', 'required': False}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('vertical', 'Vertikal tidslinje'), ('horizontal', 'Horisontal tidslinje'), ('grid', 'Grid layout')], 'help_text': 'Hvordan milepælene skal vises'}), 29: ('wagtail.blocks.StructBlock', [[('heading', 23), ('subheading', 24), ('milestones', 26), ('show_all_milestones', 27), ('timeline_style', 28), ('style', 11)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'default': 'Certificeringer & kvalifikationer', 'help_text': 'Overskrift for certificeringer sektionen', 'required': False}), 31: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse af certificeringer og kvalifikationer', 'required': False}), 32: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Certification'}), 33: ('wagtail.blocks.ListBlock', (32,), {'help_text': 'Vælg certificeringer der skal vises'}), 34: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Vis alle certificeringer automatisk (ignorerer valgte certificeringer)', 'required': False}), 35: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Skjul udløbne certificeringer', 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('heading', 30), ('subheading', 31), ('certifications', 33), ('show_all_certifications', 34), ('hide_expired', 35), ('columns', 21), ('style', 11)]], {}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'Fakta om os', 'help_text': 'Overskrift for statistik sektionen', 'required': False}), 38: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse af virksomhedens styrker', 'required': False}), 39: ('wagtail.blocks.CharBlock', (), {'help_text': "Tal eller statistik (fx '25+', '500')"}), 40: ('wagtail.blocks.CharBlock', (), {'help_text': "Beskrivelse af statistikken (fx 'År i branchen', 'Projekter gennemført')"}), 41: ('wagtail.blocks.TextBlock', (), {'help_text': 'Ekstra beskrivelse eller detaljer', 'required': False}), 42: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('calendar', 'Kalender (år)'), ('home', 'Hjem (projekter)'), ('group', 'Gruppe (team)'), ('star', 'Stjerne (kvalitet)'), ('shield', 'Skjold (sikkerhed)'), ('check', 'Check (succes)'), ('award', 'Pris (anerkendelse)'), ('clock', 'Ur (erfaring)')], 'help_text': 'Ikon der vises ved statistikken'}), 43: ('wagtail.blocks.StructBlock', [[('number', 39), ('label', 40), ('description', 41), ('icon', 42)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'help_text': 'Statistikker der skal vises'}), 45: ('wagtail.blocks.StructBlock', [[('heading', 37), ('subheading', 38), ('stats', 44), ('columns', 21), ('style', 11)]], {}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for features sektionen', 'required': False}), 47: ('wagtail.blocks.CharBlock', (), {'help_text': 'Titel for denne feature'}), 48: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivelse af featuren', 'required': False}), 49: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check', 'Checkmark'), ('hammer', 'Hammer (Håndværk)'), ('leaf', 'Leaf (Miljø)'), ('home', 'Home (Hjem)'), ('shield', 'Shield (Sikkerhed)'), ('star', 'Star (Kvalitet)'), ('clock', 'Clock (Tid)'), ('heart', 'Heart (Kærlighed)')], 'help_text': 'Ikon der vises ved siden af teksten'}), 50: ('wagtail.blocks.StructBlock', [[('title', 47), ('text', 48), ('icon', 49)]], {}), 51: ('wagtail.blocks.ListBlock', (50,), {'help_text': 'Liste af features der skal vises'}), 52: ('wagtail.blocks.StructBlock', [[('heading', 46), ('items', 51), ('columns', 21), ('style', 11)]], {}), 53: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Testimonial'}), 54: ('wagtail.blocks.ListBlock', (53,), {'help_text': 'Vælg udtalelser fra kunder der skal vises'}), 55: ('wagtail.blocks.StructBlock', [[('testimonials', 54), ('style', 11)]], {}), 56: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for call-to-action sektionen', 'required': True}), 57: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivende tekst under overskriften', 'required': False}), 58: ('wagtail.blocks.CharBlock', (), {'help_text': "Tekst på knappen (fx 'Kontakt os nu')", 'required': True}), 59: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Side som knappen linker til', 'required': True}), 60: ('wagtail.blocks.StructBlock', [[('title', 56), ('text', 57), ('button_text', 58), ('button_page', 59), ('style', 11)]], {}), 61: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for billedgalleriet', 'required': False}), 62: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Billede der skal vises'}), 63: ('wagtail.blocks.CharBlock', (), {'help_text': 'Billedtekst (valgfri)', 'required': False}), 64: ('wagtail.blocks.StructBlock', [[('image', 62), ('caption', 63)]], {}), 65: ('wagtail.blocks.ListBlock', (64,), {'help_text': 'Liste af billeder der skal vises'}), 66: ('wagtail.blocks.StructBlock', [[('heading', 61), ('images', 65), ('columns', 21), ('style', 11)]], {}), 67: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for FAQ sektionen', 'required': False}), 68: ('wagtail.blocks.CharBlock', (), {'help_text': 'Spørgsmålet der skal besvares'}), 69: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'help_text': 'Svar på spørgsmålet med mulighed for formatering'}), 70: ('wagtail.blocks.StructBlock', [[('question', 68), ('answer', 69)]], {}), 71: ('wagtail.blocks.ListBlock', (70,), {'help_text': 'Liste af spørgsmål og svar'}), 72: ('wagtail.blocks.StructBlock', [[('heading', 67), ('items', 71), ('style', 11)]], {})}, verbose_name='Indhold sektioner')),
            ],
            options={
                'verbose_name': 'Om Os Side',
                'verbose_name_plural': 'Om Os Sider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Certificering navn')),
                ('issuer', models.CharField(max_length=200, verbose_name='Udstedt af')),
                ('description', models.TextField(blank=True, verbose_name='Beskrivelse')),
                ('url', models.URLField(blank=True, verbose_name='Website URL')),
                ('expiry_date', models.DateField(blank=True, help_text='Lad være tom hvis certificeringen ikke udløber', null=True, verbose_name='Udløbsdato')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Certifikatnummer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lavere tal vises først', verbose_name='Rækkefølge')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Certificering',
                'verbose_name_plural': 'Certificeringer',
                'ordering': ['order', 'name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='År')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beskrivelse')),
                ('milestone_type', models.CharField(choices=[('founding', 'Grundlæggelse'), ('expansion', 'Udvidelse'), ('certification', 'Certificering'), ('award', 'Pris/Anerkendelse'), ('project', 'Stort projekt'), ('milestone', 'Milepæl')], default='milestone', max_length=50, verbose_name='Type')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lavere tal vises først', verbose_name='Rækkefølge')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Billede')),
            ],
            options={
                'verbose_name': 'Virksomheds milepæl',
                'verbose_name_plural': 'Virksomheds milepæle',
                'ordering': ['order', '-year'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Navn')),
                ('position', models.CharField(max_length=120, verbose_name='Stilling')),
                ('bio', models.TextField(blank=True, verbose_name='Biografi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Antal års erfaring i branchen', null=True, verbose_name='År med erfaring')),
                ('specializations', models.TextField(blank=True, help_text='Kommasepareret liste af specialiseringer', verbose_name='Specialiseringer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lavere tal vises først', verbose_name='Rækkefølge')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Teammedlem',
                'verbose_name_plural': 'Teammedlemmer',
                'ordering': ['order', 'name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
