# Generated by Django 5.0.14 on 2025-09-08 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Dit firmas officielle navn', max_length=255, verbose_name='Firmanavn')),
                ('tagline', models.CharField(blank=True, help_text="En kort beskrivelse af dit firma (f.eks. 'Kvalitet og håndværk siden 1985')", max_length=500, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, help_text='Beskrivelse af din virksomhed, historie og værdier', verbose_name='Om firmaet')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon nummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email adresse')),
                ('address', models.TextField(blank=True, help_text='Din virksomheds adresse', verbose_name='Adresse')),
                ('cvr_number', models.CharField(blank=True, max_length=20, verbose_name='CVR nummer')),
                ('established_year', models.IntegerField(blank=True, help_text='Hvilket år blev firmaet grundlagt?', null=True, verbose_name='Grundlagt år')),
            ],
            options={
                'verbose_name': 'Firma information',
                'verbose_name_plural': 'Firma information',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Navn')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=300, verbose_name='Emne')),
                ('message', models.TextField(verbose_name='Besked')),
                ('project_type', models.CharField(blank=True, choices=[('renovation', 'Renovering'), ('nybyggeri', 'Nybyggeri'), ('tilbygning', 'Tilbygning'), ('reparation', 'Reparation'), ('haandvaerk', 'Håndværk'), ('tilbud', 'Forespørgsel på tilbud'), ('andet', 'Andet')], max_length=100, verbose_name='Projekt type')),
                ('budget_range', models.CharField(blank=True, choices=[('under_50k', 'Under 50.000 kr'), ('50k_100k', '50.000 - 100.000 kr'), ('100k_250k', '100.000 - 250.000 kr'), ('250k_500k', '250.000 - 500.000 kr'), ('over_500k', 'Over 500.000 kr'), ('flexible', 'Fleksibel')], max_length=100, verbose_name='Budget interval')),
                ('is_read', models.BooleanField(default=False, verbose_name='Læst')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Besvaret')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Modtaget')),
            ],
            options={
                'verbose_name': 'Henvendelse',
                'verbose_name_plural': 'Henvendelser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="F.eks. 'Køkken renovering' eller 'Træ terrasse'", max_length=255, verbose_name='Projekt titel')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, help_text='Beskriv arbejdet, materialer og proces', verbose_name='Projekt beskrivelse')),
                ('project_type', models.CharField(choices=[('renovation', 'Renovering'), ('nybyggeri', 'Nybyggeri'), ('tilbygning', 'Tilbygning'), ('reparation', 'Reparation'), ('haandvaerk', 'Håndværk'), ('andet', 'Andet')], default='haandvaerk', max_length=100, verbose_name='Projekt type')),
                ('materials', models.TextField(blank=True, help_text="F.eks. 'Jatoba træ', 'Lærk', 'Eg', osv.", verbose_name='Materialer brugt')),
                ('client_name', models.CharField(blank=True, help_text='Valgfrit - kunde navn (anonymt eller med tilladelse)', max_length=255, verbose_name='Kunde navn')),
                ('location', models.CharField(blank=True, help_text="F.eks. 'København', 'Privat bolig', eller 'Erhverv'", max_length=255, verbose_name='Lokation')),
                ('featured', models.BooleanField(default=False, help_text='Vis dette projekt fremhævet på forsiden', verbose_name='Featured projekt')),
                ('published', models.BooleanField(default=True, help_text='Skal projektet vises på hjemmesiden?', verbose_name='Synlig på hjemmeside')),
                ('completion_date', models.DateField(blank=True, help_text='Hvornår blev projektet færdiggjort?', null=True, verbose_name='Færdiggørelse dato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Opdateret')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekter',
                'ordering': ['-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="F.eks. 'Køkken renovering', 'Træ terrasser', 'Tømrer arbejde'", max_length=200, verbose_name='Service navn')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(help_text='Detaljeret beskrivelse af servicen', verbose_name='Beskrivelse')),
                ('short_description', models.CharField(blank=True, help_text='Kort beskrivelse til service oversigt', max_length=300, verbose_name='Kort beskrivelse')),
                ('icon_class', models.CharField(blank=True, help_text="CSS ikon klasse (f.eks. 'fas fa-hammer')", max_length=50, verbose_name='Ikon klasse')),
                ('featured', models.BooleanField(default=False, help_text='Vis denne service fremhævet på forsiden', verbose_name='Fremhævet service')),
                ('active', models.BooleanField(default=True, help_text='Er denne service aktiv og tilgængelig?', verbose_name='Aktiv')),
                ('order', models.IntegerField(default=0, help_text='Rækkefølge services vises i (lavere tal = højere prioritet)', verbose_name='Rækkefølge')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Kundens navn (eller anonymt som 'Privat kunde')", max_length=200, verbose_name='Kunde navn')),
                ('title', models.CharField(blank=True, help_text="F.eks. 'Boligejer', 'Ejendomsudvikler', etc.", max_length=200, verbose_name='Kunde titel/rolle')),
                ('content', models.TextField(help_text='Kundens udtalelse om jeres arbejde', verbose_name='Testimonial')),
                ('project_title', models.CharField(blank=True, help_text="Hvilket projekt drejer testimonial'en sig om?", max_length=255, verbose_name='Relateret projekt')),
                ('rating', models.IntegerField(choices=[(1, '1 stjerner'), (2, '2 stjerner'), (3, '3 stjerner'), (4, '4 stjerner'), (5, '5 stjerner')], default=5, help_text='Antal stjerner (1-5)', verbose_name='Vurdering')),
                ('featured', models.BooleanField(default=False, help_text='Vis denne testimonial fremhævet på forsiden', verbose_name='Fremhævet testimonial')),
                ('active', models.BooleanField(default=True, help_text='Skal denne testimonial vises på hjemmesiden?', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oprettet')),
            ],
            options={
                'verbose_name': 'Kundeanmeldelse',
                'verbose_name_plural': 'Kundeanmeldelser',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%Y/%m/', verbose_name='Billede')),
                ('caption', models.CharField(blank=True, help_text='Valgfri beskrivelse af billedet', max_length=500, verbose_name='Billedtekst')),
                ('alt_text', models.CharField(blank=True, help_text='Beskrivelse for skærmlæsere', max_length=255, verbose_name='Alt tekst')),
                ('order', models.IntegerField(default=0, help_text='Rækkefølge billederne vises i', verbose_name='Rækkefølge')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cms.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projekt billede',
                'verbose_name_plural': 'Projekt billeder',
                'ordering': ['order', 'id'],
            },
        ),
    ]
