# Generated by Django 5.0.14 on 2025-09-02 16:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Intro tekst')),
                ('show_contact_form', models.BooleanField(default=True, help_text='Vis kontakt formularen på siden', verbose_name='Vis kontakt formular')),
                ('contact_form_title', models.CharField(default='Kontakt os', max_length=255, verbose_name='Formular titel')),
                ('contact_form_intro', wagtail.fields.RichTextField(blank=True, help_text='Tekst der vises over kontakt formularen', verbose_name='Formular intro tekst')),
            ],
            options={
                'verbose_name': 'Kontakt Side',
                'verbose_name_plural': 'Kontakt Sider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Beskriv dine projekter og arbejde', verbose_name='Intro tekst')),
            ],
            options={
                'verbose_name': 'Galleri Side',
                'verbose_name_plural': 'Galleri Sider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Hjemmeside', 'verbose_name_plural': 'Hjemmesider'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('trust_badges', 8), ('featured_projects', 11), ('testimonials', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Anchor id to scroll to', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('cta_text', 2), ('cta_anchor', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug of a Project to feature'}), 10: ('wagtail.blocks.StructBlock', [[('project_slug', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {})}, verbose_name='Indhold'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Intro tekst'),
        ),
    ]
