# Generated by Django 5.0.14 on 2025-09-02 20:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactpage_gallerypage_alter_homepage_options_and_more'),
        ('wagtailcore', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Valgfrit indhold før sektioner', verbose_name='Intro tekst')),
                ('theme_override', models.CharField(blank=True, choices=[('forest', 'Forest'), ('wood', 'Wood'), ('slate', 'Slate')], help_text='Valgfrit: Brug et bestemt tema for denne side', max_length=20, null=True, verbose_name='Tema (side)')),
                ('body', wagtail.fields.StreamField([('hero_v2', 11), ('cta', 13), ('features', 19), ('richtext_section', 21), ('testimonials_snippets', 24), ('logo_cloud', 27), ('services_grid', 31), ('services_grid_inline', 35), ('faq', 39), ('image_gallery', 43)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Primary CTA label', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('surface', 'Surface'), ('surface-soft', 'Surface Soft'), ('hero', 'Hero Gradient')], 'help_text': 'Section background', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide')], 'required': False}), 9: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Show a subtle top divider', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('background', 6), ('spacing', 7), ('container', 8), ('divider', 9)]], {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('primary_text', 2), ('primary_url', 3), ('secondary_text', 4), ('secondary_url', 3), ('image', 5), ('style', 10)]], {}), 12: ('wagtail.blocks.URLBlock', (), {'required': True}), 13: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_text', 0), ('button_url', 12), ('style', 10)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check', 'Check'), ('hammer', 'Hammer'), ('leaf', 'Leaf'), ('home', 'Home')]}), 16: ('wagtail.blocks.StructBlock', [[('title', 14), ('text', 1), ('icon', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')]}), 19: ('wagtail.blocks.StructBlock', [[('heading', 4), ('items', 17), ('columns', 18), ('style', 10)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote']}), 21: ('wagtail.blocks.StructBlock', [[('heading', 4), ('body', 20), ('style', 10)]], {}), 22: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Testimonial'}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('testimonials', 23), ('style', 10)]], {}), 25: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Logo'}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('logos', 26), ('style', 10)]], {}), 28: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Service'}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3')]}), 31: ('wagtail.blocks.StructBlock', [[('heading', 4), ('services', 29), ('columns', 30), ('style', 10)]], {}), 32: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check', 'Check'), ('hammer', 'Hammer'), ('home', 'Home'), ('leaf', 'Leaf')], 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('title', 14), ('description', 1), ('icon', 32)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {}), 35: ('wagtail.blocks.StructBlock', [[('heading', 4), ('items', 34), ('columns', 30), ('style', 10)]], {}), 36: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote']}), 37: ('wagtail.blocks.StructBlock', [[('question', 14), ('answer', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {}), 39: ('wagtail.blocks.StructBlock', [[('heading', 4), ('items', 38), ('style', 10)]], {}), 40: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 41: ('wagtail.blocks.StructBlock', [[('image', 40), ('caption', 4)]], {}), 42: ('wagtail.blocks.ListBlock', (41,), {}), 43: ('wagtail.blocks.StructBlock', [[('heading', 4), ('images', 42), ('columns', 18), ('style', 10)]], {})}, verbose_name='Indhold')),
            ],
            options={
                'verbose_name': 'Modul side',
                'verbose_name_plural': 'Modul sider',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quote', models.TextField()),
                ('role', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Udtalelse',
                'verbose_name_plural': 'Udtalelser',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='theme_override',
            field=models.CharField(blank=True, choices=[('forest', 'Forest'), ('wood', 'Wood'), ('slate', 'Slate')], help_text='Valgfrit: Brug et bestemt tema for denne side', max_length=20, null=True, verbose_name='Tema (side)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('trust_badges', 8), ('featured_projects', 11), ('testimonials', 13), ('hero_v2', 22), ('cta', 24), ('features', 29), ('richtext_section', 31), ('testimonials_snippets', 34), ('logo_cloud', 37), ('services_grid', 41), ('services_grid_inline', 45), ('faq', 49), ('image_gallery', 53)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Anchor id to scroll to', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('cta_text', 2), ('cta_anchor', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'template': 'blocks/trust_badges.html'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slug of a Project to feature'}), 10: ('wagtail.blocks.StructBlock', [[('project_slug', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'template': 'blocks/featured_projects.html'}), 12: ('wagtail.blocks.TextBlock', (), {}), 13: ('wagtail.blocks.ListBlock', (12,), {'template': 'blocks/testimonials_legacy.html'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Primary CTA label', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('surface', 'Surface'), ('surface-soft', 'Surface Soft'), ('hero', 'Hero Gradient')], 'help_text': 'Section background', 'required': False}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], 'required': False}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('narrow', 'Narrow'), ('normal', 'Normal'), ('wide', 'Wide')], 'required': False}), 20: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Show a subtle top divider', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('background', 17), ('spacing', 18), ('container', 19), ('divider', 20)]], {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('primary_text', 14), ('primary_url', 15), ('secondary_text', 6), ('secondary_url', 15), ('image', 16), ('style', 21)]], {}), 23: ('wagtail.blocks.URLBlock', (), {'required': True}), 24: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('button_text', 0), ('button_url', 23), ('style', 21)]], {}), 25: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check', 'Check'), ('hammer', 'Hammer'), ('leaf', 'Leaf'), ('home', 'Home')]}), 26: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 1), ('icon', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')]}), 29: ('wagtail.blocks.StructBlock', [[('heading', 6), ('items', 27), ('columns', 28), ('style', 21)]], {}), 30: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote']}), 31: ('wagtail.blocks.StructBlock', [[('heading', 6), ('body', 30), ('style', 21)]], {}), 32: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Testimonial'}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.StructBlock', [[('testimonials', 33), ('style', 21)]], {}), 35: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Logo'}), 36: ('wagtail.blocks.ListBlock', (35,), {}), 37: ('wagtail.blocks.StructBlock', [[('logos', 36), ('style', 21)]], {}), 38: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'target_model': 'pages.Service'}), 39: ('wagtail.blocks.ListBlock', (38,), {}), 40: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3')]}), 41: ('wagtail.blocks.StructBlock', [[('heading', 6), ('services', 39), ('columns', 40), ('style', 21)]], {}), 42: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('check', 'Check'), ('hammer', 'Hammer'), ('home', 'Home'), ('leaf', 'Leaf')], 'required': False}), 43: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 1), ('icon', 42)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {}), 45: ('wagtail.blocks.StructBlock', [[('heading', 6), ('items', 44), ('columns', 40), ('style', 21)]], {}), 46: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote']}), 47: ('wagtail.blocks.StructBlock', [[('question', 5), ('answer', 46)]], {}), 48: ('wagtail.blocks.ListBlock', (47,), {}), 49: ('wagtail.blocks.StructBlock', [[('heading', 6), ('items', 48), ('style', 21)]], {}), 50: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 51: ('wagtail.blocks.StructBlock', [[('image', 50), ('caption', 6)]], {}), 52: ('wagtail.blocks.ListBlock', (51,), {}), 53: ('wagtail.blocks.StructBlock', [[('heading', 6), ('images', 52), ('columns', 28), ('style', 21)]], {})}, verbose_name='Indhold'),
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logoer',
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(choices=[('forest', 'Forest'), ('wood', 'Wood'), ('slate', 'Slate')], default='forest', help_text='Standardtema for websitet (kan overstyres pr. side)', max_length=20, verbose_name='Standard tema')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Tema indstillinger',
                'verbose_name_plural': 'Tema indstillinger',
            },
        ),
    ]
