# Generated by Django 4.2.24 on 2025-09-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_sitesettings_delete_themesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='theme_override',
        ),
        migrations.RemoveField(
            model_name='modularpage',
            name='theme_override',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_theme',
            field=models.CharField(choices=[('forest', 'Forest'), ('wood', 'Wood'), ('slate', 'Slate')], default='forest', help_text='Tema for hele websitet', max_length=20, verbose_name='Standard tema'),
        ),
    ]
