# Generated by Django 5.0.14 on 2025-09-10 18:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Tekst der vises over kontakt formularen', verbose_name='Kontakt form intro'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form_title',
            field=models.CharField(default='Kontakt os', max_length=255, verbose_name='Kontakt form titel'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='show_contact_form',
            field=models.BooleanField(default=True, verbose_name='Vis kontakt formular'),
        ),
    ]
