# Generated by Django 5.0.14 on 2025-09-10 21:13

from django.db import migrations

def remove_footer_services_title_column(apps, schema_editor):
    """Remove footer_services_title column if it still exists"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='pages_sitesettings' 
            AND column_name='footer_services_title'
            AND table_schema=current_schema()
        """)
        
        if cursor.fetchone():
            # Column exists, remove it
            cursor.execute('ALTER TABLE pages_sitesettings DROP COLUMN IF EXISTS footer_services_title')
            print(f'Removed footer_services_title column from {schema_editor.connection.settings_dict.get("SCHEMA", "current schema")}')

def reverse_remove_footer_services_title_column(apps, schema_editor):
    """This is irreversible"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_sitesettings_footer_services_title_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_footer_services_title_column,
            reverse_remove_footer_services_title_column
        ),
    ]
