# Generated by Django 5.0.14 on 2025-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20250910_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_services_title',
            field=models.CharField(blank=True, default='Services', max_length=100, verbose_name='Footer services titel (deprecated)'),
        ),
    ]
