# Generated by Django 5.0.14 on 2025-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sitesettings_footer_services_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
