# Generated by Django 5.0.14 on 2025-09-11 14:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_add_font_and_preview_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form_intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Tekst der vises over kontakt formularen', verbose_name='Formular intro tekst'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_form_title',
            field=models.CharField(default='Kontakt os', max_length=255, verbose_name='Formular titel'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='show_contact_form',
            field=models.BooleanField(default=True, help_text='Vis kontakt formularen på siden', verbose_name='Vis kontakt formular'),
        ),
    ]
