# Generated by Django 5.0.14 on 2025-09-15 13:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_aboutpage_certification_companymilestone_teammember'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Kort introduktion til FAQ siden', verbose_name='Intro tekst')),
                ('body', wagtail.fields.StreamField([('hero_v2', 12), ('richtext_section', 15), ('faq', 21), ('cta', 26)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hovedoverskrift for hero sektionen', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Undertitel eller beskrivende tekst', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Tekst for primær knap (fx 'Få et tilbud')", 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Side som primær knap linker til', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Tekst for sekundær knap (fx 'Se projekter')", 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Side som sekundær knap linker til', 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Billede der vises under teksten', 'required': False}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('surface', 'Surface (Standard)'), ('surface-soft', 'Surface Soft'), ('hero', 'Hero Gradient'), ('base-200', 'Base 200'), ('base-300', 'Base 300')], 'help_text': 'Baggrundsfarve for sektionen', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small (py-10)'), ('md', 'Medium (py-16)'), ('lg', 'Large (py-24)')], 'help_text': 'Vertikal spacing for sektionen', 'required': False}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('narrow', 'Narrow (max-w-3xl)'), ('normal', 'Normal (max-w-5xl)'), ('wide', 'Wide (max-w-7xl)')], 'help_text': 'Bredde af indholdet', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Vis en subtil top divider', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('background', 7), ('spacing', 8), ('container', 9), ('divider', 10)]], {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('primary_text', 2), ('primary_page', 3), ('secondary_text', 4), ('secondary_page', 5), ('image', 6), ('style', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for tekstsektionen', 'required': False}), 14: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'help_text': 'Rich text indhold med formatering'}), 15: ('wagtail.blocks.StructBlock', [[('heading', 13), ('body', 14), ('style', 11)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for FAQ sektionen', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Spørgsmålet der skal besvares'}), 18: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote'], 'help_text': 'Svar på spørgsmålet med mulighed for formatering'}), 19: ('wagtail.blocks.StructBlock', [[('question', 17), ('answer', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'help_text': 'Liste af spørgsmål og svar'}), 21: ('wagtail.blocks.StructBlock', [[('heading', 16), ('items', 20), ('style', 11)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'Overskrift for call-to-action sektionen', 'required': True}), 23: ('wagtail.blocks.TextBlock', (), {'help_text': 'Beskrivende tekst under overskriften', 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': "Tekst på knappen (fx 'Kontakt os nu')", 'required': True}), 25: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Side som knappen linker til', 'required': True}), 26: ('wagtail.blocks.StructBlock', [[('title', 22), ('text', 23), ('button_text', 24), ('button_page', 25), ('style', 11)]], {})}, verbose_name='Indhold sektioner')),
            ],
            options={
                'verbose_name': 'FAQ Side',
                'verbose_name_plural': 'FAQ Sider',
            },
            bases=('wagtailcore.page',),
        ),
    ]
