# Generated by Django 5.0.14 on 2025-09-16 13:25

import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_gallerypage_body_gallerypage_default_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Footer', help_text='Identifikation for denne footer konfiguration', max_length=100, verbose_name='Navn')),
                ('footer_style', models.CharField(choices=[('standard', 'Standard - Fuld footer med alle sektioner'), ('minimal', 'Minimal - Kun logo og copyright'), ('centered', 'Centreret - Centreret indhold'), ('split', 'Split - Logo venstre, links højre')], default='standard', max_length=20, verbose_name='Footer stil')),
                ('background_color', models.CharField(default='#111827', help_text='Footer baggrundsfarve', max_length=7, verbose_name='Baggrundsfarve')),
                ('text_color', models.CharField(default='#9ca3af', help_text='Primær tekstfarve', max_length=7, verbose_name='Tekstfarve')),
                ('heading_color', models.CharField(default='#ffffff', help_text='Farve for sektions overskrifter', max_length=7, verbose_name='Overskrift farve')),
                ('link_color', models.CharField(default='#d1d5db', help_text='Farve for links', max_length=7, verbose_name='Link farve')),
                ('show_company_info', models.BooleanField(default=True, help_text='Vis firma beskrivelse og kontakt info', verbose_name='Vis firma information')),
                ('show_social_links', models.BooleanField(default=True, help_text='Vis sociale medie links', verbose_name='Vis sociale links')),
                ('show_quick_links', models.BooleanField(default=True, help_text='Vis navigation links i footer', verbose_name='Vis hurtige links')),
                ('show_newsletter_signup', models.BooleanField(default=False, help_text='Vis tilmeldingsformular for nyhedsbrev', verbose_name='Vis nyhedsbrev tilmelding')),
                ('newsletter_title', models.CharField(default='Tilmeld dig vores nyhedsbrev', max_length=100, verbose_name='Nyhedsbrev titel')),
                ('newsletter_description', models.TextField(default='Få de seneste nyheder og tilbud direkte i din indbakke.', verbose_name='Nyhedsbrev beskrivelse')),
                ('copyright_text', models.CharField(default='© 2025 JCleemann Byg. Alle rettigheder forbeholdes.', max_length=200, verbose_name='Copyright tekst')),
                ('footer_height', models.CharField(choices=[('auto', 'Automatisk (Standard)'), ('h-64', '256px (Fast højde)'), ('h-80', '320px (Stor højde)')], default='auto', max_length=10, verbose_name='Footer højde')),
            ],
            options={
                'verbose_name': 'Footer Indstillinger',
                'verbose_name_plural': 'Footer Indstillinger',
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Header', help_text='Identifikation for denne header konfiguration', max_length=100, verbose_name='Navn')),
                ('header_style', models.CharField(choices=[('standard', 'Standard - Klassisk navigation'), ('minimal', 'Minimal - Kun logo og navigation'), ('centered', 'Centreret - Centreret logo og navigation'), ('split', 'Split - Logo venstre, navigation højre'), ('sticky', 'Sticky - Fast navigation der følger scroll')], default='standard', max_length=20, verbose_name='Header stil')),
                ('primary_color', models.CharField(default='#4d7a3a', help_text='Hex farve kode (fx #4d7a3a)', max_length=7, verbose_name='Primær farve')),
                ('secondary_color', models.CharField(default='#6b7280', help_text='Hex farve kode for sekundær farve', max_length=7, verbose_name='Sekundær farve')),
                ('background_color', models.CharField(default='#ffffff', help_text='Header baggrundsfarve', max_length=7, verbose_name='Baggrundsfarve')),
                ('text_color', models.CharField(default='#111827', help_text='Primær tekstfarve', max_length=7, verbose_name='Tekstfarve')),
                ('show_search', models.BooleanField(default=True, help_text='Vis søgefelt i navigation', verbose_name='Vis søg')),
                ('show_theme_toggle', models.BooleanField(default=True, help_text='Vis mørk/lys tema skifter', verbose_name='Vis tema skifter')),
                ('show_cta_button', models.BooleanField(default=False, help_text='Vis call-to-action knap i navigation', verbose_name='Vis CTA knap')),
                ('cta_button_text', models.CharField(default='Kontakt os', max_length=50, verbose_name='CTA knap tekst')),
                ('cta_button_url', models.CharField(default='/kontakt/', max_length=200, verbose_name='CTA knap URL')),
                ('mobile_menu_style', models.CharField(choices=[('slide', 'Slide ind fra side'), ('dropdown', 'Dropdown fra top'), ('overlay', 'Overlay over indhold')], default='slide', max_length=20, verbose_name='Mobil menu stil')),
                ('sticky_header', models.BooleanField(default=True, help_text='Header følger scroll', verbose_name='Fast header')),
                ('header_height', models.CharField(choices=[('h-16', '64px (Standard)'), ('h-20', '80px (Stor)'), ('h-14', '56px (Kompakt)')], default='h-16', max_length=10, verbose_name='Header højde')),
            ],
            options={
                'verbose_name': 'Header Indstillinger',
                'verbose_name_plural': 'Header Indstillinger',
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Accent farve for knapper og highlights', max_length=7, verbose_name='Accent farve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Hovedbaggrundsfarve', max_length=7, verbose_name='Baggrundsfarve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='enable_color_preview',
            field=models.BooleanField(default=True, help_text='Vis farve ændringer i real-time i admin interface', verbose_name='Aktivér farve forhåndsvisning'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='error_color',
            field=models.CharField(default='#ef4444', help_text='Farve for fejl meddelelser', max_length=7, verbose_name='Fejl farve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='primary_color',
            field=models.CharField(default='#4d7a3a', help_text='Hovedfarve for websitet (hex kode fx #4d7a3a)', max_length=7, verbose_name='Primær farve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='secondary_color',
            field=models.CharField(default='#6b7280', help_text='Sekundær farve for websitet', max_length=7, verbose_name='Sekundær farve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='success_color',
            field=models.CharField(default='#10b981', help_text='Farve for succes meddelelser', max_length=7, verbose_name='Succes farve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='surface_color',
            field=models.CharField(default='#f9fafb', help_text='Farve for kort og overflader', max_length=7, verbose_name='Overflade farve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='text_primary',
            field=models.CharField(default='#111827', help_text='Hovedtekstfarve', max_length=7, verbose_name='Primær tekstfarve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='text_secondary',
            field=models.CharField(default='#6b7280', help_text='Sekundær tekstfarve', max_length=7, verbose_name='Sekundær tekstfarve'),
        ),
        migrations.AddField(
            model_name='designsettings',
            name='warning_color',
            field=models.CharField(default='#f59e0b', help_text='Farve for advarsler', max_length=7, verbose_name='Advarsel farve'),
        ),
    ]
