# Generated by Django 5.0.14 on 2025-09-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_footersettings_headersettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designsettings',
            options={'verbose_name': 'Design Indstillinger', 'verbose_name_plural': 'Design Indstillinger'},
        ),
        migrations.RemoveField(
            model_name='designsettings',
            name='site',
        ),
        migrations.AddField(
            model_name='designsettings',
            name='name',
            field=models.CharField(default='Default Design', help_text='Name for this design configuration', max_length=255),
        ),
    ]
