# Generated by Django 5.0.14 on 2025-09-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_designsettings_options_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('theme', models.CharField(choices=[('light', 'Light - Klassisk lyst design'), ('corporate', 'Corporate - Professionelt design'), ('business', 'Business - Elegant forretningsdesign'), ('emerald', 'Emerald - Naturligt og miljøvenligt design')], default='light', help_text='Vælg det visuelle tema for dit website', max_length=20, verbose_name='Tema')),
                ('font_choice', models.CharField(choices=[('inter-playfair', 'Inter + Playfair Display (Professionel)'), ('inter-georgia', 'Inter + Georgia (Klassisk)'), ('system-fonts', 'System skrifttyper (Hurtig)'), ('roboto-lora', 'Roboto + Lora (Moderne)'), ('open-sans-merriweather', 'Open Sans + Merriweather (Læsbar)')], default='inter-playfair', help_text='Skrifttype kombination for websitet', max_length=30, verbose_name='Skrifttype')),
                ('primary_color', models.CharField(default='#4d7a3a', help_text='Hovedfarve for websitet (hex kode fx #4d7a3a)', max_length=7, verbose_name='Primær farve')),
                ('secondary_color', models.CharField(default='#6b7280', help_text='Sekundær farve for websitet', max_length=7, verbose_name='Sekundær farve')),
                ('accent_color', models.CharField(default='#f59e0b', help_text='Accent farve for knapper og highlights', max_length=7, verbose_name='Accent farve')),
                ('success_color', models.CharField(default='#10b981', help_text='Farve for succes meddelelser', max_length=7, verbose_name='Succes farve')),
                ('warning_color', models.CharField(default='#f59e0b', help_text='Farve for advarsler', max_length=7, verbose_name='Advarsel farve')),
                ('error_color', models.CharField(default='#ef4444', help_text='Farve for fejl meddelelser', max_length=7, verbose_name='Fejl farve')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hovedbaggrundsfarve', max_length=7, verbose_name='Baggrundsfarve')),
                ('surface_color', models.CharField(default='#f9fafb', help_text='Farve for kort og overflader', max_length=7, verbose_name='Overflade farve')),
                ('text_primary', models.CharField(default='#111827', help_text='Hovedtekstfarve', max_length=7, verbose_name='Primær tekstfarve')),
                ('text_secondary', models.CharField(default='#6b7280', help_text='Sekundær tekstfarve', max_length=7, verbose_name='Sekundær tekstfarve')),
                ('navigation_style', models.CharField(choices=[('horizontal', 'Horisontal navigation'), ('dropdown', 'Dropdown navigation'), ('minimal', 'Minimal navigation'), ('centered', 'Centreret navigation')], default='horizontal', help_text='Hvordan skal navigationen se ud', max_length=30, verbose_name='Navigation stil')),
                ('show_navigation', models.BooleanField(default=True, help_text='Vis hovednavigation i headeren', verbose_name='Vis navigation')),
                ('show_search_in_nav', models.BooleanField(default=False, help_text='Vis søgefelt i navigation', verbose_name='Vis søg i navigation')),
                ('header_style', models.CharField(choices=[('standard', 'Standard'), ('minimal', 'Minimal'), ('centered', 'Centreret')], default='standard', help_text='Stil for headeren', max_length=20, verbose_name='Header stil')),
                ('navigation_cta_text', models.CharField(blank=True, help_text="Tekst for CTA knap i navigation (fx 'Få et tilbud')", max_length=100, verbose_name='Navigation CTA tekst')),
                ('enable_preview', models.BooleanField(default=True, help_text='Tillad forhåndsvisning af ændringer før de publiceres', verbose_name='Aktivér forhåndsvisning')),
                ('preview_url_override', models.CharField(blank=True, help_text='Valgfri specifik URL for forhåndsvisning (lad være tom for standard)', max_length=255, verbose_name='Forhåndsvisning URL')),
                ('enable_color_preview', models.BooleanField(default=True, help_text='Vis farve ændringer i real-time i admin interface', verbose_name='Aktivér farve forhåndsvisning')),
                ('navigation_cta_page', models.ForeignKey(blank=True, help_text='Side som CTA knap linker til', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_settings_cta', to='wagtailcore.page', verbose_name='Navigation CTA side')),
            ],
            options={
                'verbose_name': 'Design Indstillinger',
                'verbose_name_plural': 'Design Indstillinger',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='DesignSettings',
        ),
    ]
