# Generated by Django 5.0.14 on 2025-09-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_designpage_body_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpage',
            name='font_choice',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='theme',
        ),
    ]
