# Generated by Django 5.0.14 on 2025-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_designpage_font_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpage',
            name='theme',
            field=models.CharField(choices=[('nord', 'Nord - Arctic-inspired palette'), ('tailwind', 'Tailwind - Modern utility-first'), ('forest', 'Forest - Natural green tones'), ('ocean', 'Ocean - Deep blue palette'), ('sunset', 'Sunset - Warm orange/purple'), ('monochrome', 'Monochrome - Black and white')], default='tailwind', help_text='Vælg et foruddefineret farvetema', max_length=20, verbose_name='Tema'),
        ),
    ]
