# Generated by Django 5.0.14 on 2025-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_designpage_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designpage',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='error_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='success_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='surface_color',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='text_primary',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='text_secondary',
        ),
        migrations.RemoveField(
            model_name='designpage',
            name='warning_color',
        ),
        migrations.AlterField(
            model_name='designpage',
            name='theme',
            field=models.CharField(choices=[('nord_polar_night', 'Nord Polar Night - Dark base colors for backgrounds and text in bright designs'), ('nord_snow_storm', 'Nord Snow Storm - Bright colors for text and base UI elements'), ('nord_frost', 'Nord Frost - Bluish colors for primary UI components and syntax highlighting'), ('nord_aurora', 'Nord Aurora - Colorful components reminiscent of Aurora borealis'), ('tailwind', 'Tailwind - Modern utility-first design system with clean colors'), ('forest', 'Forest - Natural green tones inspired by Danish forests'), ('ocean', 'Ocean - Deep blue and aquatic palette'), ('sunset', 'Sunset - Warm orange, pink, and purple hues'), ('monochrome', 'Monochrome - Classic black, white, and gray scale')], default='tailwind', help_text='Vælg et foruddefineret farvetema', max_length=30, verbose_name='Tema'),
        ),
    ]
