# Generated by Django 5.0.14 on 2025-09-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_remove_designpage_accent_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='heading_color',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='link_color',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='text_color',
        ),
    ]
