# Generated by Django 5.0.14 on 2025-09-16 17:42

import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_remove_individual_color_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Navn der vises i navigation', max_length=100, verbose_name='Link navn')),
                ('url', models.CharField(help_text='Link URL (fx /om-os/ eller https://example.com)', max_length=200, verbose_name='URL')),
                ('link_type', models.CharField(choices=[('internal', 'Intern link'), ('external', 'Ekstern link'), ('email', 'Email link'), ('phone', 'Telefon link')], default='internal', max_length=20, verbose_name='Link type')),
                ('show_in_header', models.BooleanField(default=True, help_text='Vis dette link i header navigation', verbose_name='Vis i header')),
                ('show_in_footer', models.BooleanField(default=True, help_text='Vis dette link i footer navigation', verbose_name='Vis i footer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Rækkefølge i navigation (lavere tal = højere oppe)', verbose_name='Rækkefølge')),
                ('icon', models.CharField(blank=True, help_text="Heroicon navn (fx 'home', 'user', 'phone')", max_length=50, verbose_name='Ikon')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Åbn link i nyt vindue/tab', verbose_name='Åbn i nyt vindue')),
            ],
            options={
                'verbose_name': 'Navigation Link',
                'verbose_name_plural': 'Navigation Links',
                'ordering': ['order', 'name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
