# Generated by Django 5.0.14 on 2025-09-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_navigationlink'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headersettings',
            options={'ordering': ['name'], 'verbose_name': 'Header Indstillinger (Legacy)', 'verbose_name_plural': 'Header Indstillinger (Legacy)'},
        ),
        migrations.RemoveField(
            model_name='navigationlink',
            name='url',
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='aria_label',
            field=models.CharField(blank=True, help_text='Beskrivelse for skærmlæsere (valgfrit)', max_length=100, verbose_name='Tilgængeligheds beskrivelse'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='external_url',
            field=models.URLField(blank=True, help_text='Ekstern URL (fx https://example.com) - bruges kun hvis ingen intern side er valgt', verbose_name='Ekstern URL'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='highlight_as_cta',
            field=models.BooleanField(default=False, help_text='Vis dette link som en call-to-action knap', verbose_name='Fremhæv som CTA'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Valgfri CSS klasse for ikon (fx 'fas fa-home' for Font Awesome)", max_length=50, verbose_name='Ikon CSS klasse'),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='internal_page',
            field=models.ForeignKey(blank=True, help_text='Vælg en side fra dit website', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_links', to='wagtailcore.page', verbose_name='Intern side'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='link_type',
            field=models.CharField(choices=[('internal', '🏠 Intern side'), ('external', '🔗 Ekstern link'), ('email', '📧 Email link'), ('phone', '📞 Telefon link')], default='internal', help_text='Type af link - bestemmer adfærd og ikon', max_length=20, verbose_name='Link type'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='name',
            field=models.CharField(help_text='Navn der vises i navigationen', max_length=100, verbose_name='Link navn'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, help_text='Åbn linket i et nyt faneblad (anbefales for eksterne links)', verbose_name='Åbn i nyt faneblad'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Rækkefølge i navigation (lavere tal vises først)', verbose_name='Rækkefølge'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='show_in_footer',
            field=models.BooleanField(default=True, help_text='Vis dette link i footer navigationen', verbose_name='Vis i footer'),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='show_in_header',
            field=models.BooleanField(default=True, help_text='Vis dette link i header navigationen', verbose_name='Vis i header'),
        ),
        migrations.CreateModel(
            name='HeaderManagementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_style', models.CharField(choices=[('standard', 'Standard - Klassisk navigation'), ('minimal', 'Minimal - Kun logo og navigation'), ('centered', 'Centreret - Centreret logo og navigation'), ('split', 'Split - Logo venstre, navigation højre')], default='standard', help_text='Vælg overordnet stil for headeren', max_length=20, verbose_name='Header stil')),
                ('show_company_name', models.BooleanField(default=True, help_text='Vis firmanavnet ved siden af logoet', verbose_name='Vis firmanavn')),
                ('show_search', models.BooleanField(default=True, help_text='Vis søgeknap i headeren', verbose_name='Vis søg')),
                ('show_theme_toggle', models.BooleanField(default=True, help_text='Vis mørk/lys tema skifter knap', verbose_name='Vis tema skifter')),
                ('show_cta_button', models.BooleanField(default=False, help_text='Vis call-to-action knap i headeren', verbose_name='Vis CTA knap')),
                ('cta_button_text', models.CharField(default='Kontakt os', help_text='Tekst der vises på CTA knappen', max_length=50, verbose_name='CTA knap tekst')),
                ('cta_button_external_url', models.URLField(blank=True, help_text='Alternativ ekstern URL (bruges kun hvis ingen side er valgt)', verbose_name='CTA ekstern URL')),
                ('sticky_header', models.BooleanField(default=True, help_text='Header bliver fast øverst når siden scrolles', verbose_name='Fast header')),
                ('header_height', models.CharField(choices=[('py-4', 'Kompakt (16px padding)'), ('py-6', 'Standard (24px padding)'), ('py-8', 'Stor (32px padding)'), ('py-7', 'Preline standard (28px padding)')], default='py-7', help_text='Højde af headeren', max_length=10, verbose_name='Header højde')),
                ('mobile_menu_style', models.CharField(choices=[('slide', 'Slide ind fra side'), ('dropdown', 'Dropdown fra top'), ('overlay', 'Overlay over indhold')], default='slide', help_text='Hvordan skal navigation vises på mobile enheder', max_length=20, verbose_name='Mobil menu stil')),
                ('header_background_transparent', models.BooleanField(default=False, help_text='Gør header baggrunden gennemsigtig (kun for specielle designs)', verbose_name='Gennemsigtig baggrund')),
                ('hide_on_scroll', models.BooleanField(default=False, help_text='Skjul headeren når brugeren scroller ned (vises igen ved scroll op)', verbose_name='Skjul ved scroll')),
                ('preview_mode', models.CharField(choices=[('desktop', 'Desktop visning'), ('tablet', 'Tablet visning'), ('mobile', 'Mobil visning')], default='desktop', help_text='Enheds type for forhåndsvisning', max_length=20, verbose_name='Forhåndsvisning')),
                ('cta_button_page', models.ForeignKey(blank=True, help_text='Side som CTA knappen linker til', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_cta_pages', to='wagtailcore.page', verbose_name='CTA destination side')),
                ('custom_logo', models.ForeignKey(blank=True, help_text='Upload et logo billede (valgfrit - ellers bruges automatisk genereret logo)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Brugerdefineret logo')),
            ],
            options={
                'verbose_name': 'Header Administration',
                'verbose_name_plural': 'Header Administration',
            },
            bases=('wagtailcore.page',),
        ),
    ]
